OPTIONS (DIRECT=FALSE)
         LOAD DATA
         INFILE "202_022_981101.txt"
         INTO TABLE DAO.PASHA_202
   	 APPEND
   	 FIELDS TERMINATED BY '%'
   	 TRAILING NULLCOLS
    	 (ACQ_BANK,
     	 ACCEPTOR_NAME,
    	 RETURN_REASON,
    	 ADDITIONAL_DATA,
    	 AMOUNT1,
    	 CT,
    	 TRACENO,
    	 SHEBA,
    	 RCT,
    	 AMOUNT2,
    	 CYCLENO,
    	 FILE_NAME CONSTANT "202_022_981101.txt")
