OPTIONS (DIRECT=FALSE)
	 LOAD DATA
	 INFILE "206_043_981101.txt" 
	 INTO TABLE DAO.PASHA_206
	 APPEND
	 FIELDS TERMINATED BY '%'
	 TRAILING NULLCOLS
	 (TYPE,
	 SHEBA,
 	 ADDITIONAL_DATA,
 	 AMOUNT,
 	 TRACENO,
 	 CT,
 	 TRANDATE,
 	 CYCLENO,
 	 FILE_NAME CONSTANT "206_043_981101.txt")
